# https://github.com/crate-ci/typos/blob/master/docs/reference.md
[default]
locale = "en-us"
extend-ignore-re =[
  "\\.ist\\b",
  "\\bGilbert Strang\\b",
]

[type.md.extend-words]
"pgfkeys" = "pgfkeys"
"webrick" = "webrick"
"inlines" = "inlines"
